name: Metrics
on:
  # Atualiza às 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda quando há push na branch main/master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Configurações Visuais ---
          user: JoaoCarlos22
          template: classic
          config_timezone: America/Manaus
          
          base: header, activity, repositories, community
          
          # --- Plugin: Linguagens ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, ejs, handlebars
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github

          # --- Plugin: PRs e Issues ---
          plugin_followup: yes
          plugin_followup_sections: user

          # --- Plugin: Atividade recente ---
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
